### ISSUE TITLE
Extract block builder code from server into own repo

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-builder#2]
Factor out [`build_block`](https://github.com/essential-contributions/essential-server/blob/b6ad0a22254b16b5b9bb0ef524f8c96a0d3b5c53/crates/server/src/run.rs#L106) function into separate rust library in the [`essential-builder`](https://github.com/essential-contributions/essential-builder) repo.

### Description
We need to extract the `build_block` function from the server and create a new rust library for it in the `essential-node` repo. This will form the base of the builder, allowing the server to out source this functionality to the builder.

**Important:** the builder shouldn't know anything about `essential-server` as eventually it won't be used with the server.

### Tasks

- [ ] Set up a new rust library called `essential-builder` in the repository
- [ ] Add the `essential-check` dep to `essential-builder`
- [ ] Use [storage](#storage) and [transaction](#transaction) traits / types in `essential-builder`.
- [ ] Extract `build_block` function and related code from the server
- [ ] Move / add relevant tests to the new library
- [ ] Add a README
- [ ] Setup CI in the new repository
- [ ] Make the builder repo public
- [ ] Publish the builder to crates io and update the dep in the server
- [ ] Refactor server code to use the new library

### Storage trait <a href="#storage" id="storage"/>
We should try just depending on `essential-storage` and see if this works.

### Transaction <a href="#transaction" id="transaction"/>
This function currently writes state to a transaction so we will also need to make the builder depend on the `essential-transaction` repo.
